### ISSUE TITLE
Upgrade from 1.7.5.4035 --(cont-init.d) failed. Possible parsing error.

### ISSUE THREAD

**Issue by ctroncoso** [linuxserver/docker-plex#112]
This it the log of the upgrade attempt. Seems that the page changed and the regex used to parse it is failing. 
------------------------
plex           | [cont-init.d] 50-plex-update: executing...
plex           | Atempting to upgrade to: <!DOCTYPE html>
plex           | <html>
plex           | <head>
plex           |
plex           | >
plex           |
plex           |     var _gaq = _gaq || [];
plex           |     _gaq.push(['_setAccount', 'UA-6111912-23']);
plex           |     _gaq.push(['_setDomainName', 'plex.tv']);
plex           |
plex           |     (function() {
plex           |
plex           | www') + '.google-analytics.com
plex           |       var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
plex           |     })();
plex           |
plex           |
plex           |
plex           | <body>
plex           |   <div class="block">
plex           |     <div class="dialog">
plex           |
plex           |
plex           |
plex           |
plex           |
plex           | a> for current information. Thank you for your patience.<
plex           | The name is too long, 506 chars total.
plex           | Trying to shorten...
plex           | New name is plexmediaserver_<!DOCTYPE html>%0A<html>%0A<head>%0A%0A>%0A%0A    var _gaq = _gaq || [];%0A    _gaq.push(['_setAccount', 'UA-6111912-23']);%0A    _gaq.push(['_setDomainName', 'plex.tv']);%0A%0A    (function() {%0A%0Awww') + '.google-ana.
plex           | https://downloads.plex.tv/plex-media-.....[very-VERY-long-sting-of-url-encoded-nonesense]....Thank%20you%20for%20your%20patience.%3C_amd64.deb:
plex           | 2017-08-11 13:54:06 ERROR 403: Forbidden.
plex           |
plex           |
plex           |
plex           | ########################################################
plex           | # Upgrade attempt failed, this could be because either #
plex           | # plex update site is down, local network issues, or   #
plex           | # you were trying to get a version that simply doesn't #
plex           | # exist, check over the VERSION variable thoroughly &  #
plex           | # correct it or try again later.                       #
plex           | ########################################################

**Comment by aptalca** [comment]
It seems there was an issue connecting to plex servers to retrieve the latest version number. I would suggest trying again (restart the container). If it still doesn't work, you may be having network issues connecting to plex. Updates are working fine here.

**Comment by ezkialrage** [comment]
i am also having update issues. ive actually never been able to upgrade plex through restarting the container with the 'latest' flag. ive always had to destroy/rebuild the container. here is the latest log

-------------------------------------
          _     _ _
         | |___| (_) ___
         | / __| | |/ _ \
         | \__ \ | | (_) |
         |_|___/ |_|\___/
               |_|

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donations/
-------------------------------------
GID/UID
-------------------------------------
User uid:    911
User gid:    911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-dbus: executing...
[cont-init.d] 30-dbus: exited 0.
[cont-init.d] 40-chown-files: executing...
[cont-init.d] 40-chown-files: exited 0.
[cont-init.d] 50-plex-update: executing...
Atempting to upgrade to:
https://downloads.plex.tv/plex-media-server/%20/plexmediaserver_%20_amd64.deb:
2017-09-16 10:18:07 ERROR 404: Not Found.



########################################################
# Upgrade attempt failed, this could be because either #
# plex update site is down, local network issues, or   #
# you were trying to get a version that simply doesn't #
# exist, check over the VERSION variable thoroughly &  #
# correct it or try again later.                       #
########################################################

**Comment by ezkialrage** [comment]
upgrading to a specific version e.g. '1.8.4.4249-3497d6779' works though. however this is a manual process, and not automatic like i would like with the 'latest' tag. a minor inconvenience.

**Comment by j0nnymoe** [comment]
do you have -e VERSION=latest in your docker run command?

**Comment by ezkialrage** [comment]
Yes. The error appears with the environment variable set to either latest or public. Setting a specific version works though.

**Comment by j0nnymoe** [comment]
what's the docker command you run?

**Comment by ezkialrage** [comment]
I can let you know when I get home. I had to step out. I did notice that my fstab had reverted the Plex drive to 'noexec' so I fixed that but didnt get a chance to try it out again before I left.

**Comment by aptalca** [comment]
Try this in cli and see what you get:
` curl -s "https://plex.tv/downloads/latest/1?channel=8&build=linux-ubuntu-x86_64&distro=ubuntu&X-Plex-Token=yourplextoken" | cut -d "/" -f 5` but replace yourplextoken with your plex token from the Preferences.xml file in the plex config folder.

The command above should return the version number for the latest plexpass release. In your case, it's returning a bunch of nonsense. I suspect you're having some sort of a dns issue. 

Oh, and please try that command in both the host and inside the container `docker exec -it plex bash`

**Comment by ezkialrage** [comment]
so i was using OMV for my docker container. it had all the env var's set up with i downloaded this container.

![capture](https://user-images.githubusercontent.com/6233135/30517788-58e0c138-9b2f-11e7-85f7-6f9a1afc7674.PNG)

based on @aptalca 's suggestion I had to manually update the 'plex install' env var from
https://plex.tv/downloads/latest/1?channel

 to 
https://plex.tv/downloads/latest/1?channel=8&build=linux-ubuntu-x86_64&distro=ubuntu&X-Plex-Token={token}

this now works for me. upgrading automatically successfully now on latest and public release. 

you might want to add that into the readme for OMV people that they will have to update this env var because it comes in incomplete. 

thank you for helping me troubleshoot this issue ive had for a few months now.  if you are keeping this issue open because of me you can close it.

**Comment by aptalca** [comment]
I remember the dockerfile set env variables being cut off was an issue on omv. We let the omv docker plugin developer know a few months back. Didn't realize it was still an issue.

Actually, set the variable to just `https://plex.tv/downloads/latest/1?channel=8&build=linux-ubuntu-x86_64&distro=ubuntu` because the update script adds the rest of it based on whether you're signed in to plex and whether you're a plexpass user or not
